languageCode = "en"
languageName = "English"
weight = 1
title = "Joe Bollen Security"

[params]
  displayName = "EN"
  isoCode = "en"
  rtl = false
  dateFormat = "2 January 2006"
  # logo = "img/logo.png"
  # secondaryLogo = "img/secondary-logo.png"
  description = "Security insights"
  copyright = "Yes, it's a real three-body problem simulation"

