# -- Markup --
# These options configure how markdown is rendered.

[goldmark]
[goldmark.renderer]
  unsafe = true

[highlight]
  noClasses = false
  codeFences = true
  guessSyntax = true
  lineNoStart = 1
  lineNos = true
  lineNumbersInTable = true
  tabWidth = 4
  style = "native"

[tableOfContents]
  startLevel = 2
  endLevel = 4