# -- Theme Options --
# These options control how the theme functions and allow you to
# customise the display of your website.
#
# Refer to the theme docs for more details about each of these parameters.
# https://blowfish.page/docs/configuration/#theme-parameters

colorScheme = "ocean"
defaultAppearance = "dark" # valid options: light or dark
autoSwitchAppearance = false

enableSearch = false
enableCodeCopy = true

mainSections = ["posts"]
# robots = ""

disableImageOptimization = false
disableTextInHeader = false

# defaultBackgroundImage = ""
# defaultFeaturedImage = ""

highlightCurrentMenuArea = true
smartTOC = false
smartTOCHideUnfocusedChildren = false

[header]
  layout = "fixed" # valid options: basic, fixed, fixed-fill, fixed-gradient, fixed-fill-blur

[footer]
  showMenu = true
  showCopyright = true
  showThemeAttribution = false
  showAppearanceSwitcher = true
  showScrollToTop = true

[homepage]
  layout = "profile" # valid options: page, profile, hero, card, background, custom
  # homepageImage = ""
  showRecent = true
  showRecentItems = 6
  showMoreLink = true
  showMoreLinkDest = "/posts"
  cardView = true
  cardViewScreenWidth = false
  layoutBackgroundBlur = false # only used when layout equals background

[article]
  showDate = true
  showViews = false
  showLikes = false
  showDateOnlyInArticle = false
  showDateUpdated = false
  showAuthor = false
  showHero = true
  heroStyle = "basic" # valid options: basic, big, background, thumbAndBackground
  layoutBackgroundBlur = false # only used when heroStyle equals background
  layoutBackgroundHeaderSpace = true # only used when heroStyle equals background
  showBreadcrumbs = true
  showDraftLabel = true
  showEdit = false
  # editURL = "https://github.com/username/username.github.io/edit/main/content"
  editAppendPath = true
  seriesOpened = false
  showHeadingAnchors = true
  showPagination = true
  invertPagination = false
  showReadingTime = true
  showTableOfContents = true
  # showRelatedContent = false
  # relatedContentLimit = 3
  showTaxonomies = true
  showAuthorsBadges = false
  showWordCount = true
  sharingLinks = [ "linkedin", "twitter", "reddit", "email" ]
  showZenMode = true

[list]
  showHero = false
  # heroStyle = "background" # valid options: basic, big, background, thumbAndBackground
  layoutBackgroundBlur = true # only used when heroStyle equals background
  layoutBackgroundHeaderSpace = true # only used when heroStyle equals background
  showBreadcrumbs = false
  showSummary = false
  showViews = false
  showLikes = false
  showTableOfContents = false
  showCards = false
  orderByWeight = false
  groupByYear = true
  cardView = false
  cardViewScreenWidth = false
  constrainItemsWidth = false

[firebase]
  # apiKey = "XXXXXX"
  # authDomain = "XXXXXX"
  # projectId = "XXXXXX"
  # storageBucket = "XXXXXX"
  # messagingSenderId = "XXXXXX"
  # appId = "XXXXXX"
  # measurementId = "XXXXXX"

[fathomAnalytics]
  # site = "ABC12345"

[umamiAnalytics]
  # websiteid = "ABC12345"
  # datalabel = "umami"
  # dataDomains = "example.com,www.example.com"

[verification]
  # google = ""
  # bing = ""
  # pinterest = ""
  # yandex = ""

[Author]
  name = "Joe Bollen"
  image = "img/author.jpg"
  headline = "Security Insights"
  bio = "Focused on Application and AI security research."
  links = [
    { github = "https://github.com/joe-b-security" },
    { linkedin = "https://www.linkedin.com/in/joe-bollen-9b03a73a0/" }
  ]